# name: Deploy to AWS Elastic Beanstalk

# on:
#   push:
#     branches:
#       - test-changes

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Log in to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#     - name: Build and push Docker image
#       run: |
#         docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/aws_beanstalk:${{ github.sha }} .
#         docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/aws_beanstalk:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/aws_beanstalk:latest
#         docker push ${{ secrets.DOCKER_HUB_USERNAME }}/aws_beanstalk:${{ github.sha }}
#         docker push ${{ secrets.DOCKER_HUB_USERNAME }}/aws_beanstalk:latest

#     - name: Install AWS CLI
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y awscli

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ secrets.AWS_REGION }}  # AWS region

#     - name: Deploy to Elastic Beanstalk
#       run: |
#         cd .elasticbeanstalk
#         eb init -p docker ${{ secrets.EB_APP_NAME }} --region ${{ secrets.AWS_REGION }}
#         eb create ${{ secrets.EB_ENV_NAME }}
#         eb deploy ${{ secrets.EB_ENV_NAME }}
